---
apiVersion: v1
kind: Service
metadata:
  name: gatlingsolr
  namespace: namespace_filler
  labels:
    app: gatlingsolr
spec:
  ports:
  - port: 80
    name: gatlingsolr
  clusterIP: None
  selector:
    app: gatlingsolr
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gatlingsolr
  namespace: namespace_filler
spec:
  selector:
    matchLabels:
      app: gatlingsolr # has to match .spec.template.metadata.labels
  serviceName: "gatlingsolr"
  replicas: gatling-nodes-replicas
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: gatlingsolr # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      nodeSelector:
        managed-search/instance-type: n1-standard-4
        managed-search/role: solr
      tolerations:
        - effect: NoSchedule
          key: managed-search/taint
          value: solr
      containers:
      - name: gatlingsolr
        image: sarkaramrit2/gatling-solr:latest
        ports:
        - containerPort: 80
          name: gatlingsolr
        resources:
          limits:
            memory: 12G
          requests:
            cpu: 1
            memory: 8G
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OAUTH2_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: "oauth2"
                key: oauth2-client-id
          - name: OAUTH2_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: "oauth2"
                key: oauth2-client-secret
          - name: AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: "oauth2"
                key: oauth2-auth-token
        volumeMounts:
          - name: data
            mountPath: /opt/gatling/user-files/external/
  volumeClaimTemplates:
    - metadata:
        namespace: namespace_filler
        name: data
        labels:
          app: gatlingsolr
      spec:
        storageClassName: ssd
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 15Gi